"""update integrity in product catalog

Revision ID: 588dbc57c471
Revises: e61721023535
Create Date: 2024-10-04 20:01:38.805000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '588dbc57c471'
down_revision = 'e61721023535'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_catalog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_catalog', schema=None) as batch_op:
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###
